logging:
  level:
    org:
      springframework: INFO
    com:
      sap:
        olingo:
          jpa: TRACE      
odata:
  jpa:
    punit_name: Trippin
    root_packages: com.general.nitin
server:
  port: 9010
spring:
  datasource:
    url: jdbc:h2:mem:testdb;MODE=PostgreSQL
    driverClassName: org.h2.Driver
    username: sa
    password: ''
  flyway:
    enabled: true
    schemas:
    -  Trippin
  servlet:
    multipart:
      enabled: false
