logging:
  level:
    org:
      springframework: INFO
    com:
      sap:
        olingo:
          jpa: TRACE      
odata:
  jpa:
    punit_name: Trippin
    root_packages: com.general.nitin
server:
  port: 9010
spring:
  datasource:
    driver-class-name: org.hsqldb.jdbc.JDBCDriver
    password: ''
    url: jdbc:hsqldb:file:Trippin;DB_CLOSE_DELAY=-1
    username: sa
  flyway:
    password: ''
    schemas:
    - Trippin
    url: jdbc:hsqldb:file:Trippin;DB_CLOSE_DELAY=-1
    user: sa
  servlet:
    multipart:
      enabled: false
